// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmc5SKWkLMeYUdb-weNHU-r_A1p_eBHI8',
    appId: '1:188929971012:web:0f6d7528d27afc4ef23d11',
    messagingSenderId: '188929971012',
    projectId: 'connectred',
    authDomain: 'connectred.firebaseapp.com',
    storageBucket: 'connectred.appspot.com',
    measurementId: 'G-QS3R1LP05H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXhJSvBxqR01wMXMcpax-8-XrdSme6vZ8',
    appId: '1:188929971012:android:0d04e41857d96c56f23d11',
    messagingSenderId: '188929971012',
    projectId: 'connectred',
    storageBucket: 'connectred.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmc5SKWkLMeYUdb-weNHU-r_A1p_eBHI8',
    appId: '1:188929971012:web:3a4f26223780e413f23d11',
    messagingSenderId: '188929971012',
    projectId: 'connectred',
    authDomain: 'connectred.firebaseapp.com',
    storageBucket: 'connectred.appspot.com',
    measurementId: 'G-X2KKY7V0NB',
  );
}
